In [1]:
import numpy as np

---
**`compute_vector_length` compute the length of vector**
- input: vector1 and vector2
- output: dot product of two vector

> *Note: two vector must have the same shape*



In [2]:
def compute_vector_length(vector):
    return np.linalg.norm(vector)

---
**`calculate_dot_product` calculate the dot product of two vectors**
- input: vector1 and vector2
- output: dot product of two vector 

> *Note: two vector must have the same shape*



In [18]:
def calculate_dot_product(vector1, vector2):
    return np.multiply(vector1, vector2)

---
**`matrix_multiply_vector` compute the multiplication of a vector and a matrix**
- input: vector and matrix
- output: matrix with the shape (matrix columns, vector rows)

> *Note: The number of matrix's columns and vector's rows must be the same*

In [4]:
def matrix_multiply_vector(matrix, vector):
    return np.dot(matrix, vector)

---
**`matrix_multiply_matrix` Compute the multiplication of two matrixs**
- input: two matrixs
- output: matrix with the shape (matrix1 columns, matrix2 rows) 
> *Note: The number of matrix1's columns and matrix2's rows must be the same*

In [5]:
def matrix_multiply_matrix(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

---
**`inverse_matrix` computes the inverse matrix of a 2x2 matrix**

$$
\mathbf{A} = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
$$

- **Input:** a 2x2 matrix
- **Output:** the inverse matrix of the input matrix \(\mathbf{A}\)
- **Procedure:**
  1. Calculate the `determinant` of the input matrix by using the formula:  
     
      `det(A) = ad - bc`
     
     or in numpy we have the built-in function:  

     `np.linalg.det(matrix)`  

  
  2. If det(A) ≠ 0, A is invertible:  

      $$
      \mathbf{A}^{-1} = \frac{1}{\det(\mathbf{A})} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
      $$
    
     or in numpy we have the build-in function:
    
     `np.linalg.det(matrix)`  




In [6]:
def inverse_matrix(matrix):
    if np.linalg.det(matrix) == 0:
        return "This matrix cannot be inverted"
    return np.linalg.inv(matrix)

---
### Main  

In [22]:
vector1 = np.array([[1, 2, 3]])
vector2 = np.array([10, 11, 12])
vector3 = np.array([[1, 2], [3, 4]])
matrix1 = np.array([[4, 7, 10], [5, 10, 1]])
matrix2 = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18]])
square_matrix_2x2 = [[1, 2], [3, 4]]
result_1a = compute_vector_length(vector1)
result_1b = calculate_dot_product(vector1, vector2)
result_1c = matrix_multiply_vector(matrix1, vector3)
result_1d = matrix_multiply_matrix(matrix1, matrix2)
result_1e = inverse_matrix(square_matrix_2x2)
print(f'result_1a (compute_vector_length): {result_1a}\n')
print(f'result_1b (calculate_dot_product): {result_1b}\n')
print(f'result_1c (matrix_multiply_vector): \n{result_1c}\n')
print(f'result_1d (matrix_multiply_matrix): \n{result_1d}\n')
print(f'result_1e (matrix_multiply_matrix): \n{result_1e}\n')

result_1a (compute_vector_length): 3.7416573867739413

result_1b (calculate_dot_product): [[10 22 36]]

result_1c (matrix_multiply_vector): 
[[14 27 12]
 [32 61 34]]

result_1d (matrix_multiply_matrix): 
[[183 204 225 246 267 288]
 [ 88 104 120 136 152 168]]

result_1e (matrix_multiply_matrix): 
[[-2.   1. ]
 [ 1.5 -0.5]]

